# Generated by Django 6.0.5 on 2026-06-16 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_registration_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waitlist_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
